# Generated by Django 2.2.1 on 2019-06-17 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190608_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 6, 17, 20, 15, 50, 9166)),
        ),
        migrations.CreateModel(
            name='Cheklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('body', models.CharField(max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheklists', to='task.Task')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
